/*
 * ultra.c
 *
 *  Created on: Oct 13, 2022
 *      Author: felob
 */
#include "ultra.h"
#include "icu.h"
#include "gpio.h"
#include <util/delay.h>
#include"common_macros.h"
#include "avr/io.h"


/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/
uint8 g_edgeCount=0;
uint16 g_dist_Time=0;


/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*function Description:
➢ Initialize the ICU driver as required.
➢ Setup the ICU call back function.
➢ Setup the direction for the trigger pin as output pin through the
GPIO driver.*/
void Ultrasonic_init(void){
	Icu_ConfigType ICU_config={F_CPU_8,RISING};
	Icu_init(&ICU_config);
	GPIO_setupPinDirection(PORTB_ID,PIN5_ID,PIN_OUTPUT);
	GPIO_setupPinDirection(PORTD_ID,PIN6_ID,PIN_INPUT);
	Icu_setCallBack(Ultrasonic_edgeProcessing);
}

/*function Description:
➢ Send the Trigger pulse to the ultrasonic..*/
void Ultrasonic_Trigger(void){
	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_LOW);
}

/*function Description:
➢ Send the trigger pulse by using Ultrasonic_Trigger function.
➢ Start the measurements by the ICU from this moment.
*/
uint16 Ultrasonic_readDistance(void){
	uint16 distance=0;
	Ultrasonic_Trigger();
	distance=(uint16)((float32) g_dist_Time/57.8);
	if(distance<57){
		distance++;
	}
	return distance;
}


/*function Description:
This is the call back function called by the ICU driver.
➢ This is used to calculate the high time (pulse time) generated by
the ultrasonic sensor.
*/
void Ultrasonic_edgeProcessing(void){
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_dist_Time = Icu_getInputCaptureValue();
		Icu_clearTimerValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
		g_edgeCount=0;
	}

}

